title: UX Maturity
author: L. Tang
email: ltang8@kent.edu
description: > # this means to ignore newlines until "baseurl:"
  Blog focusing on my personal experience evangelizing UX design 
  and helping to push for a more mature UX design organization.

# social links
github_username:  ltux

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
